### ISSUE TITLE
MnInput - add attribute name

### ISSUE THREAD

**Issue by darlanmendonca** [reserva-facil/minimalist#12]
lets add support to attribute `name`, e.g.

```html
<form name="formName" id="formID>
  <mn-input name="username" />
</form>
```

So, in the form, we need assign a getter, example

```js
// following codes need return the value of mn-input, a empty string, or typed string
formName.username.value
formID.username.value
```

**Comment by darlanmendonca** [comment]
@alencar13 lets do it first? you can start the specs before implementation

**Comment by alencar13** [comment]
Yes, I'm implementing this attribute first.

**Comment by darlanmendonca** [comment]
nice, when you finish some specs, put the branch where you're working here pls
