### ISSUE TITLE
MnInput - add support to attribute placeholder

### ISSUE THREAD

**Issue by darlanmendonca** [reserva-facil/minimalist#13]
we need to offer a placeholder, reason, native placeholder of input, dont be fully styled, e.g., I want move placeholder to top, instead hide(default behavior of native placeholder)

we need write our component

```html
<mn-input placeholder="test" />
```

in "compiled/computed" component, the dom will be anything similar to

```html
<mn-input placeholder="test">
  <label>test</label> <!-- as a tag, we can style completely, with css -->
  <input />
</mn-input>
```

example styled by our css

![preview](https://cloud.githubusercontent.com/assets/876227/26165773/8c73b83a-3b07-11e7-8f72-121fa2d1f3cb.gif)

**Comment by alencar13** [comment]
Starting specs writing.
