### ISSUE TITLE
Add feature `npm t` to execute in all browsers

### ISSUE THREAD

**Issue by alencar13** [reserva-facil/minimalist#3]
Actually if I execute `npm t` it's executing just one package of tests. 

The idea is like `npm t all` command but executing just in existing browsers.

So, I think that's better to insert in `npm t` the feature of executing in **multiple browsers** and only in **existing browsers in that OS**.

What do you think about it @darlanmendonca ?

**Comment by darlanmendonca** [comment]
I like, is more intuitive, run `npm t` and run test in all things, and `npm t chrome` if in a single browser.

Lets implement this, later
