### ISSUE TITLE
run specifics tests

### ISSUE THREAD

**Issue by darlanmendonca** [reserva-facil/minimalist#9]
script test allow arguments passed after --, to the process (karma), example

npm test -- --grep=mn-input

where --grep is a argument passed to karma

greep is to filter tests, and run only matched
but for any reason dont work, we need resolve this

maybe be a problem in karma, or karma-mocha, I do know, need a investigation

**Comment by alencar13** [comment]
It's a great behavior run in specifics arguments! 
Any news I'll let you know.
